language: php
dist: trusty

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

branches:
  only:
    - master

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - ./vendor/bin/phpunit -c phpunit.ci.xml

notifications:
  email:
    recipients:
      - codedungeon@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
